name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Angular App to EC2
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build:ssr

      - name: Zip Built Output (SSR)
        run: |
          cd dist/ecommerencefrontend
          zip -r ~/ecommerencefrontend.zip .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true

      - name: Upload to EC2
        run: |
          scp -o StrictHostKeyChecking=no ~/ecommerencefrontend.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/ecommerencefrontend.zip

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "✅ Connected to EC2. Starting deployment..."

            # Delete old files and zip
            rm -rf ~/ecommerencefrontend
            rm -f ~/ecommerencefrontend.zip

            # Move new zip & unzip
            mv ~/ecommerencefrontend.zip ~/ecommerencefrontend.zip
            unzip -o ~/ecommerencefrontend.zip -d ~/ecommerencefrontend

            cd ~/ecommerencefrontend

            # Docker cleanup
            docker stop ecommerencefrontend || true
            docker rm ecommerencefrontend || true
            docker rmi ecommerencefrontend || true

            # Rebuild and run
            docker build -t ecommerencefrontend .
            docker run -d -p 8081:80 --name ecommerencefrontend ecommerencefrontend

            echo "✅ Deployment complete and old files cleaned."
          EOF
