name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true

      - name: Test SSH Connection
        run: |
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo connected"

      - name: Debug SSH Key
        run: |
          ls -l ~/.ssh
          file ~/.ssh/id_rsa
          head -5 ~/.ssh/id_rsa
          tail -5 ~/.ssh/id_rsa

      - name: Debug Secrets
        run: |
          echo "EC2_USER: ${{ secrets.EC2_USER }}"
          echo "EC2_HOST: ${{ secrets.EC2_HOST }}"
          echo "EC2_KEY: [hidden]"

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} <<-'EOF'
            echo "✅ Connected to EC2 and starting deployment..."

            cd ~/ecommerencefrontend

            # Stop and remove existing container
            docker stop ecommerencefrontend || true
            docker rm ecommerencefrontend || true

            # Remove old image (optional)
            docker rmi ecommerencefrontend || true

            # Build and run with the same name and port
            docker build -t ecommerencefrontend .
            docker run -d -p 8081:80 --name ecommerencefrontend ecommerencefrontend

            echo "✅ Frontend redeployed successfully."
          EOF
