name: Deploy Angular App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Angular App to EC2
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular App
        run: npm run build --prod

      - name: Zip Dist Folder
        run: |
          mkdir docker-deploy
          cp -r dist/ecommerencefrontend docker-deploy/
          cp Dockerfile docker-deploy/
          cd docker-deploy && zip -r app.zip .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true

      - name: Upload to EC2
        run: |
          scp -o StrictHostKeyChecking=no docker-deploy/app.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app.zip

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            echo "✅ Connected to EC2. Starting deploy..."

            rm -rf ~/ecommerencefrontend
            unzip -o ~/app.zip -d ~/ecommerencefrontend
            cd ~/ecommerencefrontend

            docker stop ecommerencefrontend || true
            docker rm ecommerencefrontend || true
            docker rmi ecommerencefrontend || true

            docker build -t ecommerencefrontend .
            docker run -d -p 8081:80 --name ecommerencefrontend ecommerencefrontend

            echo "✅ Deployment finished."
          EOF
